CREATE DATABASE IF NOT EXISTS bangladesh_locations; 
USE bangladesh_locations; 
DROP TABLE IF EXISTS areas; 
CREATE TABLE areas ( id INT AUTO_INCREMENT PRIMARY KEY, area_name VARCHAR(100) NOT NULL, district_name VARCHAR(100) NOT NULL );
INSERT INTO areas (area_name, district_name) VALUES
('Aftab Nagar', 'Dhaka'),
('Agargaon', 'Dhaka'),
('Azimpur', 'Dhaka'),
('Badda', 'Dhaka'),
('Banani', 'Dhaka'),
('Baridhara', 'Dhaka'),
('Bashundhara', 'Dhaka'),
('Demra', 'Dhaka'),
('Gulshan', 'Dhaka'),
('Kafrul', 'Dhaka'),
('Kalabagan', 'Dhaka'),
('Khilgaon', 'Dhaka'),
('Mirpur', 'Dhaka'),
('Mohammadpur', 'Dhaka'),
('Motijheel', 'Dhaka'),
('Pallabi', 'Dhaka'),
('Shahbagh', 'Dhaka'),
('Tejgaon', 'Dhaka'),
('Uttara', 'Dhaka'),
('Wari', 'Dhaka'),
('Airport', 'Barishal'),
('Kaunia', 'Barishal'),
('Kotwali', 'Barishal'),
('Bandar', 'Barishal'),
('Agailjhara', 'Barishal'),
('Babuganj', 'Barishal'),
('Bakerganj', 'Barishal'),
('Barishal Sadar', 'Barishal'),
('Gournadi', 'Barishal'),
('Hizla', 'Barishal'),
('Mehendiganj', 'Barishal'),
('Muladi', 'Barishal'),
('Wazirpur', 'Barishal'),
('South Pahartali', 'Chattogram'),
('Jalalabad', 'Chattogram'),
('Panchlaish', 'Chattogram'),
('Chandgaon', 'Chattogram'),
('Mohra', 'Chattogram'),
('East Sholashahar', 'Chattogram'),
('West Sholashahar', 'Chattogram'),
('Sholokbahar', 'Chattogram'),
('North Pahartali', 'Chattogram'),
('North Kattali', 'Chattogram'),
('South Kattali', 'Chattogram'),
('Saraipara', 'Chattogram'),
('Pahartali', 'Chattogram'),
('Lalkhan Bazar', 'Chattogram'),
('Bagmaniram', 'Chattogram'),
('Chawkbazar', 'Chattogram'),
('West Bakalia', 'Chattogram'),
('East Bakalia', 'Chattogram'),
('South Bakalia', 'Chattogram'),
('Dewan Bazar', 'Chattogram'),
('Jamal Khan', 'Chattogram'),
('Enayet Bazar', 'Chattogram'),
('North Pathantooly', 'Chattogram'),
('North Agrabad', 'Chattogram'),
('Rampur', 'Chattogram'),
('North Halishahar', 'Chattogram'),
('South Agrabad', 'Chattogram'),
('Pathantooly', 'Chattogram'),
('West Madarbari', 'Chattogram'),
('East Madarbari', 'Chattogram'),
('Alkaran', 'Chattogram'),
('Andarkilla', 'Chattogram'),
('Firingee Bazar', 'Chattogram'),
('Patharghata', 'Chattogram'),
('Boxirhat', 'Chattogram'),
('Gosaildanga', 'Chattogram'),
('North Middle Halishahar', 'Chattogram'),
('South Middle Halishahar', 'Chattogram'),
('South Halishahar', 'Chattogram'),
('North Patenga', 'Chattogram'),
('South Patenga', 'Chattogram'),
('Anwara', 'Chattogram'),
('Banshkhali', 'Chattogram'),
('Boalkhali', 'Chattogram'),
('Chandanaish', 'Chattogram'),
('Fatikchhari', 'Chattogram'),
('Hathazari', 'Chattogram'),
('Karnaphuli', 'Chattogram'),
('Lohagara', 'Chattogram'),
('Mirsharai', 'Chattogram'),
('Patiya', 'Chattogram'),
('Raozan', 'Chattogram'),
('Rangunia', 'Chattogram'),
('Sandwip', 'Chattogram'),
('Satkania', 'Chattogram'),
('Sitakunda', 'Chattogram'),
('Banikpara', 'Khulna'),
('Senpara', 'Khulna'),
('Kartikkul', 'Khulna'),
('Deana', 'Khulna'),
('Daulatpur Bazar', 'Khulna'),
('Pabla', 'Khulna'),
('North Kashipur', 'Khulna'),
('The Peoples Jute Mills', 'Khulna'),
('Mujgunni', 'Khulna'),
('Nayabati', 'Khulna'),
('Khalishpur Housing East Block', 'Khulna'),
('Khalishpur Housing South Block', 'Khulna'),
('Platinum Jute Mills', 'Khulna'),
('East Boyra', 'Khulna'),
('Polytechnic', 'Khulna'),
('C&B Colony', 'Khulna'),
('New Market', 'Khulna'),
('Shibbari', 'Khulna'),
('Goborchaka', 'Khulna'),
('Sheikhpara', 'Khulna'),
('BIWTA Ghat', 'Khulna'),
('Custom Ghat', 'Khulna'),
('Baitipara', 'Khulna'),
('Iqbal Nagar', 'Khulna'),
('Basupara', 'Khulna'),
('West Baniakhamar', 'Khulna'),
('East Baniakhamar', 'Khulna'),
('West Tootpara', 'Khulna'),
('Haji Mohsin Road', 'Khulna'),
('Tootpara', 'Khulna'),
('Labanchara', 'Khulna'),
('Koyra', 'Khulna'),
('Dacope', 'Khulna'),
('Paikgachha', 'Khulna'),
('Batiaghata', 'Khulna'),
('Phultala', 'Khulna'),
('Dumuria', 'Khulna'),
('Terokhada', 'Khulna'),
('Dighalia', 'Khulna'),
('Rupsa', 'Khulna'),
('Shah Makhdum', 'Rajshahi'),
('Laxmipur', 'Rajshahi'),
('Motihar', 'Rajshahi'),
('Boalia', 'Rajshahi'),
('Kazla', 'Rajshahi'),
('Shaheb Bazar', 'Rajshahi'),
('Bogra Bazar', 'Rajshahi'),
('Paba', 'Rajshahi'),
('Tanore', 'Rajshahi'),
('Bagha', 'Rajshahi'),
('Godagari', 'Rajshahi'),
('Puthia', 'Rajshahi'),
('Charghat', 'Rajshahi'),
('Bagmara', 'Rajshahi'),
('Mohonpur', 'Rajshahi'),
('Durgapur', 'Rajshahi'),
('Rajpara', 'Rajshahi'),
('Chapai Nawabganj Sadar', 'Rajshahi'),
('Shibganj', 'Rajshahi'),
('Nachole', 'Rajshahi'),
('Rangpur Sadar', 'Rangpur'),
('Kaunia', 'Rangpur'),
('Gangachhara', 'Rangpur'),
('Badarganj', 'Rangpur'),
('Mithapukur', 'Rangpur'),
('Pirgachha', 'Rangpur'),
('Pirganj', 'Rangpur'),
('Taraganj', 'Rangpur'),
('Hakimpur', 'Rangpur'),
('Gangachhara', 'Rangpur'),
('Patiya', 'Rangpur'),
('Dimla', 'Rangpur'),
('Debiganj', 'Rangpur'),
('Thakurgaon Sadar', 'Rangpur'),
('Boda', 'Rangpur'),
('Biral', 'Rangpur'),
('Panchagarh Sadar', 'Rangpur'),
('Atwari', 'Rangpur'),
('Tetulia', 'Rangpur'),
('Kaliganj', 'Rangpur'),
('Mymensingh Sadar', 'Mymensingh'),
('Trishal', 'Mymensingh'),
('Bhaluka', 'Mymensingh'),
('Muktagachha', 'Mymensingh'),
('Phulpur', 'Mymensingh'),
('Gaffargaon', 'Mymensingh'),
('Ishwarganj', 'Mymensingh'),
('Nandail', 'Mymensingh'),
('Haluaghat', 'Mymensingh'),
('Dhobaura', 'Mymensingh'),
('Zindabazar', 'Sylhet'),
('Kumargaon', 'Sylhet'),
('Alurchala', 'Sylhet'),
('Ambarkhana', 'Sylhet'),
('Subidbazar', 'Sylhet'),
('South Surma', 'Sylhet'),
('Balaganj', 'Sylhet'),
('Beanibazar', 'Sylhet'),
('Fenchuganj', 'Sylhet'),
('Golapganj', 'Sylhet'),
('Gowainghat', 'Sylhet'),
('Jaintiapur', 'Sylhet'),
('Kanaighat', 'Sylhet'),
('Osmani Nagar', 'Sylhet'),
('Sylhet Sadar', 'Sylhet'),
('Dakshin Surma', 'Sylhet'),
('Jalalabad', 'Sylhet');





